# Server
server:
  port: 8763
 
#spring
spring: 
  data: 
    mongodb: 
      uri: mongodb://bapuser:bapuser123@192.168.4.122:27017/amcloud
      database: amcloud

#cxf

cxf: 
  path: /api/soap

#ws
ws: 
  equipservice:
    resturl: http://localhost:${server.port}/api/rest/service
  packservice:
    resturl: http://localhost:${server.port}/api/rest/packservice
  erpservice:
    resturl: http://localhost:${server.port}/api/rest/erpservice
  wmsservice:
    resturl: http://localhost:${server.port}/api/rest/wmsservice
      
#httpclient
httpclient: 
  config: 
    proxy: false
    proxyhost:
    proxyPort: 8080
    maxConnTotal: 10000  
    maxPerRoute: 500  
    connectTimeout: 5000
    connectRequestTimeout: 5000   
    socketTimeout: 10000

eureka:
  instance:
    metadata-map:
      user.name: user
      user.password: ${REGISTRY_SERVER_PASSWORD:password}

security:
  Basic: 
    enable: false
management: 
  security: 
    enabled: false
